---
functional:
 - Пользователь должен иметь возможность искать товары по ключевому слову или категории
 - Пользователь должен иметь возможность фильтровать товары
 - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
 - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
 
non-functional:
 - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт должен иметь мобильную версию
 - Сайт нужно протестировать на совместимость с последними версиями браузеров
 - Важно, чтобы сайт мог обрабатывать большое количество трафика
 - Сайт должен быть доступен на различных устройствах
implicit:
- При перезагрузке страницы не должен сбрасываться выбранный язык сайта
- При оформлении заказа, менеджер сайта доложен иметь возможность связаться с клиентом
- Ручной поиск должен работать по компаниям, а не только по продукту
- В корзине должно отображаться название товара, количество и цена товара, а под этим должно отображаться значение
- При очищении корзины должно вылезать подтверждение
- При удалении товара из корзины должно вылезать подтверждение
- При добавлении товара в корзину должно вылезать модульное окно с вариантом выбора количества добавленого товара
- В варианте выбора категории должен быть выбор со всеми товарами
- В карточке товара должна имется возможность вернуться обратно в магазин
- В карточке товара должна имется возможность просмотреть фотографии товара
- В карточке товара должна имется возможность нажав на выбранный хэштэг, вернутся в магазин где отображенны все товара с данным хэштэгом
- Описание в карточке товара сделать в виде таблицы
- Каждая цифра в карточке товара должна быть подписана
